<!DOCTYPE html>
<html dir="ltr" lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ ucfirst($group) }} Report</title>
    <style>
        * { box-sizing: border-box; margin: 0; padding: 0; }
        body { font-family: DejaVu Sans, sans-serif; font-size: 10px; color: #1a1a2e; background: #fff; padding: 20px; }
        h1 { font-size: 18px; color: #1E4D8C; margin-bottom: 4px; }
        .subtitle { font-size: 10px; color: #666; margin-bottom: 20px; }
        h2 { font-size: 13px; color: #1E4D8C; border-bottom: 2px solid #1E4D8C; padding-bottom: 4px; margin: 16px 0 8px; }
        .kpi-grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 10px; margin-bottom: 16px; }
        .kpi { background: #f0f5ff; border-left: 3px solid #1E4D8C; padding: 8px 10px; border-radius: 3px; }
        .kpi-label { font-size: 9px; color: #555; text-transform: uppercase; letter-spacing: .5px; }
        .kpi-value { font-size: 14px; font-weight: bold; color: #1E4D8C; margin-top: 2px; }
        table { width: 100%; border-collapse: collapse; margin-bottom: 14px; font-size: 9px; }
        th { background: #1E4D8C; color: #fff; padding: 5px 6px; text-align: left; }
        td { padding: 4px 6px; border-bottom: 1px solid #e8e8e8; }
        tr:nth-child(even) td { background: #f8faff; }
        .footer { margin-top: 20px; font-size: 9px; color: #888; border-top: 1px solid #ddd; padding-top: 8px; }
        .section-label { font-size: 9px; font-weight: bold; text-transform: uppercase; color: #888; margin-bottom: 4px; }
    </style>
</head>
<body>
    <h1>{{ ucfirst($group) }} Report</h1>
    <div class="subtitle">Generated at {{ now()->format('Y-m-d H:i') }}</div>

    @foreach ($data as $sectionKey => $sectionData)
        <h2>{{ ucwords(str_replace('_', ' ', $sectionKey)) }}</h2>

        @if ($sectionKey === 'summary')
            <div class="kpi-grid">
                @foreach ($sectionData as $field => $value)
                    @if ($field !== 'generated_at' && !is_array($value))
                        <div class="kpi">
                            <div class="kpi-label">{{ str_replace('_', ' ', $field) }}</div>
                            <div class="kpi-value">{{ is_float($value) ? number_format($value, 2) : $value }}</div>
                        </div>
                    @endif
                @endforeach
            </div>
        @else
            @php $rows = $sectionData['data'] ?? $sectionData; @endphp
            @if (!empty($rows) && is_array($rows) && is_array(reset($rows)))
                <table>
                    <thead>
                        <tr>
                            @foreach (array_keys(reset($rows)) as $col)
                                <th>{{ ucwords(str_replace('_', ' ', $col)) }}</th>
                            @endforeach
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($rows as $row)
                            <tr>
                                @foreach ($row as $cell)
                                    <td>{{ is_array($cell) ? json_encode($cell) : $cell }}</td>
                                @endforeach
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            @endif
        @endif
    @endforeach

    <div class="footer">Report generated by Taearif Platform &mdash; {{ now()->toISOString() }}</div>
</body>
</html>
