<?php

return [
	'guard' => 'sanctum',
	'rbac_version' => 1,

	'permissions' => [
        'live_editor.view',
        'live_editor.update',
        'dashboard.view',
        'dashboard.update',
        'content.view',
        'content.update',
        'settings.view',
        'settings.update',
        'apps.view',
        'apps.update',
        'affiliate.view',
        'affiliate.update',

		'customers.view',
        'customers.create',
        'customers.update',
        'customers.delete',

		'projects.view',
        'projects.create',
        'projects.update',
        'projects.delete',

		'properties.view',
        'properties.create',
        'properties.update',
        'properties.delete',
        'properties.owner_deed',

		'crm.view',
        'crm.create',
        'crm.update',
        'crm.delete',
		'rentals.view',
        'rentals.create',
        'rentals.update',
        'rentals.delete',
		'buildings.view',
        'buildings.create',
        'buildings.update',
        'buildings.delete',

		'property_requests.view',
        'property_requests.create',
        'property_requests.update',
        'property_requests.delete',

		'job_applications.view',
        'job_applications.create',
        'job_applications.update',
        'job_applications.delete',

		'customers_hub_analytics.view',
		'customers_hub_analytics.create',
		'customers_hub_analytics.update',
		'customers_hub_analytics.delete',

		'customers_hub_requests.view',
		'customers_hub_requests.create',
		'customers_hub_requests.update',
		'customers_hub_requests.delete',

		'customers_hub_customers.view',
		'customers_hub_customers.create',
		'customers_hub_customers.update',
		'customers_hub_customers.delete',

		'customers_hub_pipeline.view',
		'customers_hub_pipeline.create',
		'customers_hub_pipeline.update',
		'customers_hub_pipeline.delete',

		'customers_hub_ai_matching.view',
		'customers_hub_ai_matching.create',
		'customers_hub_ai_matching.update',
		'customers_hub_ai_matching.delete',

		// Pixels
		'pixels.view',
		'pixels.create',
		'pixels.update',
		'pixels.delete',

		// WhatsApp Center — Numbers
		'whatsapp_center_numbers.view',
		'whatsapp_center_numbers.create',
		'whatsapp_center_numbers.update',
		'whatsapp_center_numbers.delete',

		// WhatsApp Center — Campaigns
		'whatsapp_center_campaigns.view',
		'whatsapp_center_campaigns.create',
		'whatsapp_center_campaigns.update',
		'whatsapp_center_campaigns.delete',

		// WhatsApp Center — Templates
		'whatsapp_center_templates.view',
		'whatsapp_center_templates.create',
		'whatsapp_center_templates.update',
		'whatsapp_center_templates.delete',

		// WhatsApp Chat
		'whatsapp_chat.view',
		'whatsapp_chat.create',

		// SMS Campaigns
		'sms_campaigns.view',
		'sms_campaigns.create',
		'sms_campaigns.update',
		'sms_campaigns.delete',

		// Email Campaigns
		'email_campaigns.view',
		'email_campaigns.create',
		'email_campaigns.update',
		'email_campaigns.delete',

		// Blogs
		'blogs.view',
		'blogs.create',
		'blogs.update',
		'blogs.delete',

		// Employees
		'employees.view',
		'employees.create',
		'employees.update',
		'employees.delete',
	],

	'role_templates' => [
		'owner' => [
			'customers.view',
            'customers.create',
            'customers.update',
            'customers.delete',
			'projects.view',
            'projects.create',
            'projects.update',
            'projects.delete',
			'properties.view',
            'properties.create',
            'properties.update',
            'properties.delete',
            'properties.owner_deed',
			'crm.view',
            'crm.create',
            'crm.update',
            'crm.delete',
			'content.view',
			'settings.view',
			'settings.update',
			'apps.view',
			'affiliate.view',
			'affiliate.update',
			'rentals.view',
            'rentals.create',
            'rentals.update',
            'rentals.delete',
			'buildings.view',
            'buildings.create',
            'buildings.update',
            'buildings.delete',
			'property_requests.view',
            'property_requests.create',
            'property_requests.update',
            'property_requests.delete',
			'job_applications.view',
            'job_applications.create',
            'job_applications.update',
            'job_applications.delete',
		],
		'manager' => [
			'customers.view',
            'customers.create',
            'customers.update',
			'projects.view',
            'projects.create',
            'projects.update',
			'properties.view',
            'properties.create',
            'properties.update',
			'crm.view',
            'crm.create',
            'crm.update',
			'content.view',
			'settings.view',
			'settings.update',
			'apps.view',
			'rentals.view',
            'rentals.create',
            'rentals.update',
            'rentals.delete',
			'buildings.view',
            'buildings.create',
            'buildings.update',
            'buildings.delete',
			'property_requests.view',
            'property_requests.create',
            'property_requests.update',
            'property_requests.delete',
			'job_applications.view',
            'job_applications.create',
            'job_applications.update',
            'job_applications.delete',
		],
		'agent' => [
			'customers.view',
            'customers.create',
			'projects.view',
            'projects.create',
			'properties.view',
            'properties.create',
			'crm.view',
            'crm.create',
			'content.view',
			'settings.view',
			'apps.view',
			'rentals.view',
            'buildings.view',
            'property_requests.view',
            'job_applications.view',
		],
	],
];
