<?php

return [
	'guard' => 'sanctum',
	'rbac_version' => 1,

	'permissions' => [
        'live_editor.view',
        'dashboard.view',
        'content.view',
        'settings.view',
        'apps.view',
        'affiliate.view',

		'customers.view',
        'customers.create',
        'customers.update',
        'customers.delete',

		'projects.view',
        'projects.create',
        'projects.update',
        'projects.delete',

		'properties.view',
        'properties.create',
        'properties.update',
        'properties.delete',

		'content.view',

		'crm.view',
        'crm.create',
        'crm.update',
        'crm.delete',
	],

	'role_templates' => [
		'owner' => [
			'customers.view',
            'customers.create',
            'customers.update',
            'customers.delete',
			'projects.view',
            'projects.create',
            'projects.update',
            'projects.delete',
			'properties.view',
            'properties.create',
            'properties.update',
            'properties.delete',
			'content.view',
            'content.create',
            'content.update',
            'content.delete',
			'crm.view',
            'crm.create',
            'crm.update',
            'crm.delete',
			'settings.view',
		],
		'manager' => [
			'customers.view',
            'customers.create',
            'customers.update',
			'projects.view',
            'projects.create',
            'projects.update',
			'properties.view',
            'properties.create',
            'properties.update',
			'content.view',
            'content.create',
            'content.update',
			'crm.view',
            'crm.create',
            'crm.update',
			'settings.view',
		],
		'agent' => [
			'customers.view',
            'customers.create',
			'projects.view',
            'projects.create',
			'properties.view',
            'properties.create',
			'content.view',
            'content.create',
			'crm.view',
            'crm.create',
			'settings.view',
		],
	],
];
