<?php

return [
    // Phase 1: Apps
    'App\Http\Controllers\Api\App\ApiInstallationController@install' => [
        'app_id' => 'required|integer|exists:api_apps,id',
        'settings' => 'nullable|array',
        'settings.phone_number' => 'nullable|string|max:20',
        'settings.token' => 'nullable|string|max:255',
    ],
    'App\Http\Controllers\Api\App\ApiInstallationController@uninstall' => [],
    'App\Http\Controllers\Api\App\ApiInstallationController@uninstallWhatsapp' => [],

    // Phase 5: V1 Marketing, RMS, SMS, Tenant, WhatsApp, V2 CustomersHub, WhatsApp app
    'App\Http\Controllers\Api\marketing\MarketingChannelController@syncVerified' => [],
    'App\Http\Controllers\Api\marketing\MarketingChannelController@whatsappWebhook' => [],
    'App\Http\Controllers\Api\V1\Rms\ReminderController@dismiss' => [],
    'App\Http\Controllers\Api\V1\Rms\InstallmentController@regenerate' => [],
    'App\Http\Controllers\Api\V1\Rms\RentalController@reversePayment' => [],
    'App\Http\Controllers\Api\V1\Sms\WebhookController@delivery' => [],
    'App\Http\Controllers\Api\V1\TenantWebsite\PublishController@store' => [],
    'App\Http\Controllers\Api\V1\WhatsApp\AiConfigController@toggle' => [],
    'App\Http\Controllers\Api\V1\WhatsApp\AutomationRuleController@toggle' => [],
    'App\Http\Controllers\Api\V1\WhatsApp\ConversationController@read' => [],
    'App\Http\Controllers\Api\V1\WhatsApp\ConversationController@star' => [],
    'App\Http\Controllers\Api\V1\WhatsApp\WebhookController@incoming' => [],
    'App\Http\Controllers\Api\V1\WhatsApp\WebhookController@status' => [],
    'App\Http\Controllers\Api\V1\WhatsApp\WebhookController@verifyPost' => [],
    'App\Http\Controllers\Api\V2\CustomersHub\ListController@bulk' => [],
    'App\Http\Controllers\Api\V2\CustomersHub\RequestsController@complete' => [],
    'App\Http\Controllers\Api\V2\CustomersHub\RequestsController@dismiss' => [],
    'App\Http\Controllers\Api\V2\CustomersHub\RequestsController@markListViewed' => [],
    'Modules\WhatsappAI\Http\Controllers\ConversationController@archive' => [],
    'Modules\WhatsappAI\Http\Controllers\WebhookController@handle' => [],
    'App\Http\Controllers\Api\apps\whatsapp\WhatsappAddonController@store' => [],
    'App\Http\Controllers\Api\apps\whatsapp\ChatController@handleEvolutionWebhook' => [],
    'App\Http\Controllers\Api\apps\whatsapp\WhatsappController@store' => [],
    'App\Http\Controllers\Api\apps\whatsapp\ChatController@handleWhatsappWebhook' => [],
    'App\Http\Controllers\Api\apps\whatsapp\WhatsappController@updateEmployee' => [],
    'App\Http\Controllers\Api\apps\whatsapp\WhatsappController@link' => [],
    'App\Http\Controllers\Api\apps\whatsapp\WhatsappController@unlink' => [],

    // Swagger unresolved warnings: callbacks, webhooks, and action-only POST endpoints.
    'App\Http\Controllers\Api\marketing\CreditController@paymentSuccess' => [
        'trandata' => 'nullable|string',
        'payment_id' => 'nullable|string|max:255',
        'transaction_id' => 'nullable|string|max:255',
        'result' => 'nullable|string|max:255',
        'payment_result' => 'nullable|string|max:255',
        'status' => 'nullable|string|max:255',
        'error' => 'nullable|string|max:1000',
        'payment_error' => 'nullable|string|max:1000',
    ],
    'App\Http\Controllers\Api\marketing\CreditController@paymentCancel' => [
        'trandata' => 'nullable|string',
        'payment_id' => 'nullable|string|max:255',
        'transaction_id' => 'nullable|string|max:255',
        'result' => 'nullable|string|max:255',
        'payment_result' => 'nullable|string|max:255',
        'status' => 'nullable|string|max:255',
        'reason' => 'nullable|string|max:255',
        'error' => 'nullable|string|max:1000',
        'payment_error' => 'nullable|string|max:1000',
    ],
    'App\Http\Controllers\Api\V1\Email\CampaignController@pause' => [],
    'App\Http\Controllers\Api\V1\Email\WebhookController@delivery' => [
        'provider' => 'nullable|string|max:255',
        'user_id' => 'nullable|integer',
        'gateway_message_id' => 'nullable|string|max:255',
        'status' => 'nullable|string|in:delivered,failed,undelivered,rejected,bounced,spam,complained',
        'error_message' => 'nullable|string|max:1000',
        'delivered_at' => 'nullable|date',
        'events' => 'nullable|array',
    ],
    'App\Http\Controllers\Api\property\ApiPropertyRequestController@storeFromInterest' => [
        'tenant_username' => 'required|string|max:255',
        'property_id' => 'required|integer|exists:user_properties,id',
        'full_name' => 'required|string|max:255',
        'phone' => 'required|string|max:20',
        'notes' => 'nullable|string|max:1000',
    ],
    'App\Http\Controllers\Api\V1\Sms\CampaignController@pause' => [],
    'App\Http\Controllers\Api\V1\WhatsApp\CampaignController@pause' => [],

    // Runtime FormRequest (user + route); explicit map so swagger:generate-api-paths does not warn
    'App\Http\Controllers\Api\property\PropertyRequestStatusController@store' => [
        'name_ar' => 'required|string|max:100',
        'name_en' => 'nullable|string|max:100',
        'slug' => 'required|string|max:100',
        'display_order' => 'nullable|integer|min:1',
        'is_active' => 'nullable|boolean',
    ],
    'App\Http\Controllers\Api\property\PropertyRequestStatusController@update' => [
        'name_ar' => 'sometimes|required|string|max:100',
        'name_en' => 'nullable|string|max:100',
        'slug' => 'sometimes|required|string|max:100',
        'display_order' => 'nullable|integer|min:1',
        'is_active' => 'nullable|boolean',
    ],
    'App\Http\Controllers\Api\V2\CustomersHub\RequestsController@markRead' => [],
    'App\Http\Controllers\Api\V2\CustomersHub\RequestsController@markUnread' => [],
    'App\Http\Controllers\Api\V2\CustomersHub\RequestsController@ignore' => [
        'is_ignored' => 'nullable|boolean',
    ],
    'App\Http\Controllers\Api\V2\CustomersHub\RequestsController@rematch' => [],
];
