<?php

$base = [

    /*
    |--------------------------------------------------------------------------
    | Swagger request body rules (docs only)
    |--------------------------------------------------------------------------
    |
    | Maps controller@method to validation rules used only for OpenAPI docs.
    | Key: 'App\\Http\\Controllers\\...\\Controller@method'
    | Value: class-string with static rulesForDocs(): array, or direct rules array.
    | Used when the controller uses inline $request->validate() so rules cannot
    | be discovered by FormRequest reflection.
    |
    */

    'App\Http\Controllers\Api\Affiliate\AffiliateController@register' => [
        'fullname'             => 'required|string|max:255',
        'bank_name'            => 'required|string|max:255',
        'bank_account_number'  => 'required|string|max:30',
        'iban'                 => 'required|string|max:34',
    ],

    'App\Http\Controllers\Api\Customer\CustomerController@store' => [
        'name'         => 'required|string|max:255',
        'email'        => 'nullable|email',
        'phone_number' => 'required|string|max:20',
        'city_id'      => 'nullable|integer',
        'district_id'  => 'nullable|integer',
        'note'         => 'nullable|string',
        'type_id'      => 'required|integer',
        'responsible_employee_id' => 'nullable|integer',
        'stage_id'     => 'nullable|integer',
        'procedure_id' => 'nullable|integer',
        'password'     => 'nullable|string|min:6',
        'interested_category_ids'   => 'nullable|array',
        'interested_category_ids.*' => 'integer',
        'interested_property_ids'   => 'nullable|array',
        'interested_property_ids.*' => 'integer',
    ],

    'App\Http\Controllers\Api\Customer\CustomerController@update' => [
        'name'         => 'sometimes|string|max:255',
        'email'        => 'nullable|email',
        'phone_number' => 'sometimes|string|max:20',
        'city_id'      => 'nullable|integer',
        'district_id'  => 'nullable|integer',
        'note'         => 'nullable|string',
        'type_id'      => 'nullable|integer',
        'stage_id'     => 'nullable|integer',
        'responsible_employee_id' => 'nullable|integer',
        'procedure_id' => 'nullable|integer',
        'password'     => 'nullable|string|min:6',
        'interested_category_ids'   => 'nullable|array',
        'interested_category_ids.*' => 'integer',
        'interested_property_ids'   => 'nullable|array',
        'interested_property_ids.*' => 'integer',
    ],

    'App\Http\Controllers\Api\project\ProjectController@store' => [
        'featured_image'   => 'required|string',
        'video_url'       => 'nullable|string',
        'address'         => 'nullable|string',
        'description'     => 'nullable|string|min:15',
        'complete_status' => 'nullable|string',
        'units'           => 'nullable|integer',
        'completion_date' => 'nullable|date',
        'developer'       => 'nullable|string|max:255',
        'gallery_images'     => 'nullable|array',
        'gallery_images.*'   => 'nullable|string',
        'floorplan_images'   => 'nullable|array',
        'floorplan_images.*' => 'nullable|string',
        'min_price' => 'nullable|numeric',
        'max_price' => 'nullable|numeric',
        'featured' => 'nullable|boolean',
        'status'   => 'nullable|string',
        'latitude'  => 'nullable|numeric',
        'longitude' => 'nullable|numeric',
        'label' => 'nullable|array',
        'value' => 'nullable|array',
    ],

    'App\Http\Controllers\Api\project\ProjectController@update' => [
        'featured_image'   => 'required|string',
        'video_url'       => 'nullable|string',
        'address'         => 'nullable|string',
        'description'     => 'nullable|string|min:15',
        'gallery_images'     => 'sometimes|array',
        'gallery_images.*'   => 'string',
        'floorplan_images'   => 'sometimes|array',
        'floorplan_images.*' => 'string',
        'min_price' => 'nullable|numeric',
        'max_price' => 'nullable|numeric',
        'featured' => 'sometimes|boolean',
        'status'   => 'sometimes|string',
        'latitude'  => 'nullable|numeric',
        'longitude' => 'nullable|numeric',
        'label' => 'nullable|array',
        'value' => 'nullable|array',
        'complete_status' => 'nullable|string',
        'units' => 'nullable|integer',
    ],

    'App\Http\Controllers\Api\property\PropertyController@store' => [
        'payment_method'       => 'nullable|string',
        'title'                => 'required|string|max:255',
        'address'              => 'required|string',
        'description'          => 'required|string',
        'featured_image'       => 'required|string',
        'gallery'              => 'nullable|array',
        'gallery.*'            => 'string',
        'floor_planning_image' => 'nullable|string',
        'video_image'          => 'nullable|string',
        'video_url'            => 'nullable|string',
        'virtual_tour'         => 'nullable|string',
        'price'                => 'nullable|numeric',
        'pricePerMeter'        => 'nullable|numeric',
        'beds'                  => 'nullable|string',
        'bath'                  => 'nullable|string',
        'purpose'               => 'nullable|string',
        'area'                  => 'nullable|string',
        'status'                => 'nullable|string',
        'latitude'              => 'nullable|numeric',
        'longitude'             => 'nullable|numeric',
        'project_id'            => 'nullable|string',
        'city_id'               => 'nullable|string',
        'state_id'              => 'nullable|string',
        'featured'              => 'nullable|boolean',
        'amenities'             => 'nullable|array',
        'type'                  => 'nullable|string',
        'faqs'                  => 'nullable|array',
        'category_id'           => 'nullable|integer',
        'facade_id'             => 'nullable|numeric',
        'length'                => 'nullable|numeric',
        'width'                 => 'nullable|numeric',
        'street_width_north'    => 'nullable|numeric',
        'street_width_south'    => 'nullable|numeric',
        'street_width_east'     => 'nullable|numeric',
        'street_width_west'     => 'nullable|numeric',
        'building_age'         => 'nullable|integer',
        'rooms'                 => 'nullable|integer',
        'bathrooms'             => 'nullable|integer',
        'floors'                => 'nullable|integer',
        'floor_number'          => 'nullable|integer',
        'driver_room'           => 'nullable|integer',
        'maid_room'             => 'nullable|integer',
        'dining_room'           => 'nullable|integer',
        'living_room'           => 'nullable|integer',
        'majlis'                => 'nullable|integer',
        'storage_room'          => 'nullable|integer',
        'basement'              => 'nullable|integer',
        'swimming_pool'          => 'nullable|integer',
        'kitchen'                => 'nullable|integer',
        'balcony'                => 'nullable|integer',
        'garden'                 => 'nullable|integer',
        'annex'                  => 'nullable|integer',
        'elevator'               => 'nullable|integer',
        'private_parking'        => 'nullable|integer',
        'size'                   => 'nullable|integer',
        'building_id'            => 'nullable|integer',
        'water_meter_number'     => 'nullable|string',
        'electricity_meter_number' => 'nullable|string',
        'deed_number'            => 'nullable|string',
        'advertising_license'   => 'nullable|string',
        'owner_number'           => 'nullable|string',
        'video_file'             => 'nullable|string',
    ],

    'App\Http\Controllers\Api\property\PropertyController@update' => [
        'payment_method'       => 'nullable|string',
        'title'                => 'required|string|max:255',
        'address'              => 'required|string',
        'description'          => 'required|string',
        'featured_image'       => 'required|string',
        'gallery'              => 'nullable|array',
        'gallery.*'            => 'string',
        'floor_planning_image' => 'nullable|string',
        'video_image'          => 'nullable|string',
        'price'                => 'nullable|numeric',
        'pricePerMeter'        => 'nullable|numeric',
        'beds'                  => 'nullable|string',
        'bath'                  => 'nullable|string',
        'purpose'               => 'nullable|string',
        'area'                  => 'nullable|string',
        'status'                => 'nullable|string',
        'latitude'              => 'nullable|numeric',
        'longitude'             => 'nullable|numeric',
        'project_id'            => 'nullable|string',
        'city_id'               => 'nullable|string',
        'state_id'              => 'nullable|string',
        'amenities'             => 'nullable|array',
        'category_id'           => 'nullable|integer',
        'facade_id'             => 'nullable|numeric',
        'length'                => 'nullable|numeric',
        'width'                 => 'nullable|numeric',
        'street_width_north'    => 'nullable|numeric',
        'street_width_south'    => 'nullable|numeric',
        'street_width_east'     => 'nullable|numeric',
        'street_width_west'     => 'nullable|numeric',
        'building_age'          => 'nullable|integer',
        'rooms'                 => 'nullable|integer',
        'bathrooms'             => 'nullable|integer',
        'floors'                => 'nullable|integer',
        'floor_number'          => 'nullable|integer',
        'driver_room'           => 'nullable|integer',
        'maid_room'             => 'nullable|integer',
        'dining_room'           => 'nullable|integer',
        'living_room'           => 'nullable|integer',
        'majlis'                => 'nullable|integer',
        'storage_room'          => 'nullable|integer',
        'basement'              => 'nullable|integer',
        'swimming_pool'          => 'nullable|integer',
        'kitchen'                => 'nullable|integer',
        'balcony'                => 'nullable|integer',
        'garden'                 => 'nullable|integer',
        'annex'                  => 'nullable|integer',
        'elevator'               => 'nullable|integer',
        'private_parking'        => 'nullable|integer',
        'size'                   => 'nullable|integer',
        'building_id'            => 'nullable|integer',
        'water_meter_number'    => 'nullable|string',
        'electricity_meter_number' => 'nullable|string',
        'deed_number'            => 'nullable|string',
        'advertising_license'   => 'nullable|string',
        'owner_number'          => 'nullable|string',
    ],

];

$extended = file_exists(__DIR__ . '/swagger_request_map_extended.php')
    ? require __DIR__ . '/swagger_request_map_extended.php'
    : [];

return array_merge($extended, $base);
